feat: Upload dir async (#855)
* feature: upload dir and keep dir structure

* docs: example upload dir and keep dir structure

* feat: switch to async

* feat: use pause and resume to await directory before file

* feat: handle cases when directoryName is already an existing file

* docs: describe options.createDirsFromUpload

* fix: async await

* fix: formatting https://github.com/node-formidable/formidable/pull/855#discussion_r898621934

* tests: adapt tests

* fix: too many tests us this port at the same time

* tests: update sha1 (added linebreak)

* test: update special chars

we decode # encoded things now ?

* test: force carriage return and use fetch

* test: force async,

* test: remove unused

* test: move, use node for tests in test-node

* test: try to fix jest error

* test: update and fix custom plugin fail

* test: disable this test, cannot understand the error

    ReferenceError: require is not defined

       8 |   size: 1024,
       9 |   filepath: '/tmp/cat.png',
    > 10 |   name: 'cat.png',
         |       ^
      11 |   type: 'image/png',
      12 |   lastModifiedDate: now,
      13 |   originalFilename: 'cat.png',

      at _getJestObj (test/unit/persistent-file.test.js:10:7)
      at test/unit/persistent-file.test.js:19:1

* test: detect problematic test case, comment out (todo)

* test: add test case for createDirsFromUploads option

* test: semicolons and others

* chore: version and changelog

* feat: test command runs all tests at once

* chore: update node version for testing

* chore: up dependencies like in v2

https://github.com/node-formidable/formidable/commit/9afd5f801b1728f80e7e293f5e3774b43f1d1fc5

* chore: mark as latest on npm