test: disable this test, cannot understand the error
    ReferenceError: require is not defined

       8 |   size: 1024,
       9 |   filepath: '/tmp/cat.png',
    > 10 |   name: 'cat.png',
         |       ^
      11 |   type: 'image/png',
      12 |   lastModifiedDate: now,
      13 |   originalFilename: 'cat.png',

      at _getJestObj (test/unit/persistent-file.test.js:10:7)
      at test/unit/persistent-file.test.js:19:1